### ISSUE TITLE
[BUG] Remove HTML from meta: Description

### ISSUE THREAD

**Issue by shawnthompson** [gc-da11yn/gc-da11yn.github.io#128]
## Required information

**Describe the bug**
When compiled the `description` front matter goes into the [`meta:description`](https://github.com/gc-da11yn/gc-da11yn.github.io/blob/main/src/_includes/partials/head.njk#L10).

If there's `HTML` in the front matter it gets added to the `value` of the `meta:description`

Example:

```
---
title: Statistics Canada (StatCan)
layout: layouts/base.njk
description: Statistics Canada, in collaboration with partners from Employment and Social Development Canada, will continue to develop and release products to better understand the accessibility experiences of Canadians. The <a href="https://www.statcan.gc.ca/en/topics-start/accessibility">Accessibility Data Hub</a> provides a centralized location of topics related to accessibility and disability through data tables, articles, infographics and interactive data visualization tools.
---
```

**To Reproduce**
Steps to reproduce the behaviour:
1. add a link in a page's `description` front matter
2. compile the `HTML`
3. View the source of the rendered page

``` html
<meta name="description" content="Statistics Canada, in collaboration with partners from Employment and Social Development Canada, will continue to develop and release products to better understand the accessibility experiences of Canadians. The 

&lt;a href=&quot;https://www.statcan.gc.ca/en/topics-start/accessibility&quot;&gt;Accessibility Data Hub&lt;/a&gt; 

provides a centralized location of topics related to accessibility and disability through data tables, articles, infographics and interactive data visualization tools.">
```

**Expected behaviour**
Find a way to strip the `HTML` out of the rendered `meta` element

**Who shall do the work?**
The Development team

## Additional information (optional)

We would should do the same for the `title` front matter.

**Comment by kimviens** [comment]
This bug is not clear. Why are you trying to add HTML in the meta:description? Do you want to repurpose the front matter description to use elsewhere AND in the meta:description? It looks like to me its a user error to put HTML in the description

**Comment by shawnthompson** [comment]
Fixed in https://github.com/gc-da11yn/gc-da11yn.github.io/pull/201/commits/51df2402a8d376e484f94d31261f2ee1551ac64a

**Comment by shawnthompson** [comment]
@kimviens Sorry I didn't even see your comment. To clarify, we use the `title` and `descriptions` values in content as well as in the `head` of the page. So we want to remove the `html` elements when we are using the the values in the `head`.

We did this by using the Nunjucks filter: [striptags (value, [preserve_linebreaks])](https://mozilla.github.io/nunjucks/templating.html#striptags-value-preserve_linebreaks).
