### ISSUE TITLE
[BUG] External hyperlinks - open in same tab instead of new tab

### ISSUE THREAD

**Issue by lynelal** [gc-da11yn/gc-da11yn.github.io#163]
## Required information

**Describe the bug**
If you found another bug report related to this issue on GitHub, please mention its number e.g. #7890

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://a11y.canada.ca/en/guides/virtual-meetings/.'
2. Click on 'hyperlinks'
3. See error - When hyperlinking to an external site, shouldn't the browser open a new tab?

**Expected behaviour**
Hyperlinks to external sites from a11Y.canada.ca stay on the same tab rather than opening a new tab.  I don't think this is correct.  I believe the page should open in a new tab.

**Who shall do the work?**
[I will do it, I want to contribute] or [I am asking for someone else to please do the work]

## Additional information (optional)

**Version of gc-da11yn you are using**
e.g. v1.0.0

**Desktop/Smartphone (please complete the following information)**
 - OS or Device: [e.g. iOS]

**Screenshots**
If applicable, add screenshots to help explain the bug.

**Additional context**

**Comment by shawnthompson** [comment]
Links should always open in the tab unless it you are in a process and you could lose information you have already entered.

Opening external links used to be a process awhile back on the web but became an accessibility issue.

WCAG has this technique: [Opening new windows and tabs from a link only when necessary](https://www.w3.org/TR/WCAG20-TECHS/G200.html).

@lynelal if this answers your concerns, could I ask you to close this issue or continue the conversation.

Thank you very much,
Shawn

**Comment by lynelal** [comment]
Thanks Shawn.
