### ISSUE TITLE
[CHANGE] Short description of page

### ISSUE THREAD

**Issue by JTCFPPSC** [gc-da11yn/gc-da11yn.github.io#181]
## Required information

**What page is the change request for? Please supply the URL.**

URL: https://a11y.canada.ca/en/sampling/thanks/ 

**Attach Word document with track changes enabled for required change(s).**
N/A

**Approval needed?**

- [ ] No
- [ ] Yes, I need to approve this request before change goes live
- [ ] Yes, please send a request to the following person: INSERT_NAME_HERE
- [X] Unsure

**Who shall do the work?**

- [ ] I will do it, I want to contribute
- [X] I am asking for someone else to please do the work

## Additional information (optional)

**Timeline**
Is there a deadline attached to this request? If so, please briefly describe why and provide a date (YYYY-MM-DD)
No timeline

**Screenshots**
Indicated issue in yellow
![Annotation 2022-07-26 090021](https://user-images.githubusercontent.com/110036293/181012073-ab5a9533-a1df-41c4-825d-1a474ffbc5ae.jpg)

**Additional context**
Spelling Mistake on the "Thank you for completing the User Persona Survey" page
![Annotation 2022-07-26 090021](https://user-images.githubusercontent.com/110036293/181012073-ab5a9533-a1df-41c4-825d-1a474ffbc5ae.jpg)

**Comment by shawnthompson** [comment]
Thanks I'll fix that mistake.
