### ISSUE TITLE
ADD Spell checking

### ISSUE THREAD

**Issue by gcharest** [gc-da11yn/gc-da11yn.github.io#200]
## Required information

**Is your feature request related to a problem? Please describe.**
Basic spellchecking should be done when developing to minimize spelling mistakes in production.

**Describe the solution you'd like**
Add and configure cspell for French and English files

**Describe alternatives you've considered**
Don't make spelling mistakes...

**Who shall do the work?**
I guess I should look into this... @gcharest 

## Additional information (optional)

**Timeline**
Sometime after this issue is created... 

**Screenshots**

**Additional context**
See PR #199 for an example of spellings that could have been caught by cspell.

**Comment by shawnthompson** [comment]
I'm going to close this and we will look into it creating a list once we put it in a testing,
