### ISSUE TITLE
[BROKEN LINK] background document

### ISSUE THREAD

**Issue by MaddyDaigle** [gc-da11yn/gc-da11yn.github.io#231]
## Required information

**What page is the broken link found on? Please supply the URL.**

URL: https://a11y.canada.ca/en/standards/standard/

**Link text of the link**

Text: [background document](https://a11y.canada.ca/en/standards/standard/backgrounder)

**New `href` for the link**

URL: https://a11y.canada.ca/en/standards/backgrounder/

**Approval needed?**

- [ ] No
- [ ] Yes, I need to approve this request before change goes live
- [ ] Yes, please send a request to the following person: INSERT_NAME_HERE

**Who shall do the work?**

- [ ] I will do it, I want to contribute
- [x] I am asking for someone else to please do the work

## Additional information (optional)

**Timeline**

Is there a deadline attached to this request? If so, please briefly describe why and provide a date (YYYY-MM-DD)
N/A

**Screenshots**
<img width="1094" alt="Screen Shot 2022-11-13 at 1 00 31 PM" src="https://user-images.githubusercontent.com/1794660/201537012-e8b4e2a3-97e4-4a6a-8066-62c72066c7ed.png">

**Additional context**

N/A

**Comment by shawnthompson** [comment]
Thanks for reporting this, we are fixing it now.
