### ISSUE TITLE
Professional Language

### ISSUE THREAD

**Issue by EDunn613** [gc-da11yn/gc-da11yn.github.io#255]
"Our soon to be awesome site is new and still under construction" is unprofessional language and sounds like it was written by a high school student.  We are the Government of Canada - being "trendy and cool" is not a goal, clear communication of information is.

**Comment by shawnthompson** [comment]
We appreciate the input, would you have any suggestion?

**Comment by EDunn613** [comment]
Good morning Shawn,

Do you not have any Comms people?


Erica Dunn
Senior Policy Analyst | Office of the Superintendent of Bankruptcy
Innovation, Science and Economic Development Canada | Government of Canada
***@***.******@***.***> | Tel : (613) 301-6380

Analyste principale des politiques | Bureau du surintendant des faillites
Innovation, sciences et développement économique Canada | Gouvernement du Canada
***@***.******@***.***> | Tél: (613) 301-6380

**Comment by shawnthompson** [comment]
Are official launch is Sunday December 3rd, 2023. The alert will be removed.
