### ISSUE TITLE
Remove SSC branding from posters

### ISSUE THREAD

**Issue by bsouster** [gc-da11yn/gc-da11yn.github.io#263]
### What page is the change request for? Please supply the URI.

https://a11y.canada.ca/en/guides/

### Approval needed?

Yes, I need to approve this request before change goes live

### Who shall do the work?

- [ ] I will do it, I want to contribute
- [X] I am asking for someone else to please do the work

### Additional context

The request involves making edits to the PDFs (English AND French):
* [Designing for users on the autistic spectrum](https://a11y.canada.ca/docs/posters/AutismSpect-en.pdf)
* [Design principles for users with cognitive disabilities](https://a11y.canada.ca/docs/posters/Cognitive-en.pdf)
* [Designing for users who are deaf or hard of hearing](https://a11y.canada.ca/docs/posters/Hearing-en.pdf)
* [Designing for users with low vision](https://a11y.canada.ca/docs/posters/LowVision-en.pdf)
* [Designing for users with physical or motor disabilities](https://a11y.canada.ca/docs/posters/MotorPhysical-en.pdf)
* [Designing for users of screen readers](https://a11y.canada.ca/docs/posters/ScreenReader-en.pdf)

There needs to be Government of Canada branding instead of SSC branding

**Comment by shawnthompson** [comment]
SSC would need to make the change and attach the new PDFs to this issue. They could also supply the DAT with original files used to create the PDFs and someone who has the knowledge can make the change.

Are these that much different than the ones the UK created? Could we just not use them instead?

I also like the way the UK presents them on their website.

[Accessibility posters](https://ukhomeoffice.github.io/accessibility-posters/)

They have HTML content and the posters are just one downloadable file in stead of breaking them up into separate files for people to choose which one they want. 

They also have [French versions](https://github.com/UKHomeOffice/posters/tree/master/accessibility/dos-donts/posters_en-UK/svg) of their posters.

Thoughts on this, @JulieBB23 and the content group?

**Comment by JulieBB23** [comment]
Allo,

The content has been reviewed once, just need a second review to confirm the content is final and then we can look at the layout, I do like the layout from UK that you shared Shawn.

**Comment by nricherbrule** [comment]
Here are the new PDF docs for the site.

P.S. Shawn, you're awesome!
[SpectreAutistique-fr_2023.pdf](https://github.com/gc-da11yn/gc-da11yn.github.io/files/12362214/SpectreAutistique-fr_2023.pdf)
[AutismSpect-en_2023.pdf](https://github.com/gc-da11yn/gc-da11yn.github.io/files/12362215/AutismSpect-en_2023.pdf)
[Cognitif-fr_2023.pdf](https://github.com/gc-da11yn/gc-da11yn.github.io/files/12362216/Cognitif-fr_2023.pdf)
[Cognitive-en_2023.pdf](https://github.com/gc-da11yn/gc-da11yn.github.io/files/12362217/Cognitive-en_2023.pdf)
[Hearing-en_2023.pdf](https://github.com/gc-da11yn/gc-da11yn.github.io/files/12362218/Hearing-en_2023.pdf)
[LowVision-en_2023.pdf](https://github.com/gc-da11yn/gc-da11yn.github.io/files/12362219/LowVision-en_2023.pdf)
[Malvoyants-fr_2023.pdf](https://github.com/gc-da11yn/gc-da11yn.github.io/files/12362220/Malvoyants-fr_2023.pdf)
[MoteurPhysique-fr_2023.pdf](https://github.com/gc-da11yn/gc-da11yn.github.io/files/12362221/MoteurPhysique-fr_2023.pdf)
[MotorPhysical-en_2023.pdf](https://github.com/gc-da11yn/gc-da11yn.github.io/files/12362222/MotorPhysical-en_2023.pdf)
[RevuesDecran-fr_2023.pdf](https://github.com/gc-da11yn/gc-da11yn.github.io/files/12362223/RevuesDecran-fr_2023.pdf)
[ScreenReader-en_2023.pdf](https://github.com/gc-da11yn/gc-da11yn.github.io/files/12362224/ScreenReader-en_2023.pdf)
[Sourds-fr_2023.pdf](https://github.com/gc-da11yn/gc-da11yn.github.io/files/12362225/Sourds-fr_2023.pdf)

**Comment by shawnthompson** [comment]
Will need to compare to the files in the text version on the [Designing accessible services - Digital Accessibility Toolkit / Sharing space](https://a11y.canada.ca/en/guides/design-accessible-services/) page.

**Comment by shawnthompson** [comment]
@nricherbrule the French heading on the Cognitive poster does not match the others.

They say "À FAIRE" an "À NE PAS FAIRE" while the other posters say "CHOSES À FAIRE" and "CHOSE À NE PAS FAIRE".

Could you please supply us with new posters that have the same headings as the other posters?

Thanks

**Comment by nricherbrule** [comment]
@shawnthompson 
[Cognitif-fr_2023.pdf](https://github.com/gc-da11yn/gc-da11yn.github.io/files/12419378/Cognitif-fr_2023.pdf)
Here is the updated file
