### ISSUE TITLE
[BUG] Fix Typos

### ISSUE THREAD

**Issue by gcharest** [gc-da11yn/gc-da11yn.github.io#265]
### Describe the bug

**To Reproduce**

1. Locally run `npm run spellcheck`
2. Check the console for spelling mistakes
3. Fix the mistakes OR add exceptions to corresponding dictionaries

**Expected behaviour**
Should not have any spelling mistakes listed.

**Who shall do the work?**
@gcharest will have a crack at it first

**Comment by shawnthompson** [comment]
Closed by #266
