### ISSUE TITLE
JSON naming convention

### ISSUE THREAD

**Issue by gcharest** [gc-da11yn/gc-da11yn.github.io#27]
Propose using the [Google JSON Naming convention](https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Property_Name_Format#Property_Name_Format).

Example from [footer.js](https://github.com/gc-da11yn/gc-da11yn.github.io/blob/main/src/_data/footer.js):

```JSON
fr: {
    "Aboutgovernment": "Au sujet du gouvernement",
    "Contactus": "Contactez-nous"
}
```

Would become:

```JSON
fr: {
    "aboutGovernment": "Au sujet du gouvernement",
    "contactUs": "Contactez-nous"
}
```

Makes it easier to read the properties, supposed to be readable by most screen readers and supports automated parsing for refactoring in case it's needed :smile:

**Comment by shawnthompson** [comment]
PR away young Jedi!
