### ISSUE TITLE
[CHANGE] Short description of page

### ISSUE THREAD

**Issue by lynelal** [gc-da11yn/gc-da11yn.github.io#275]
### What page is the change request for? Please supply the URI.

https://a11y.canada.ca/en/guides/

### Approval needed?

None

### Who shall do the work?

- [ ] I will do it, I want to contribute
- [X] I am asking for someone else to please do the work

### Additional context

I recommend changing the wording for the following hyperlinks and the titles of the pages
From:  "Assessible documents guide: Office 365"
To: "Assessible content guide: Microsoft 365"

From: "Assessible document guide: Office 2016"
To: "Assessible content guide: Office 2016"

Reasoning: 
1. Office 365 was recently renamed to Microsoft 365 by Microsoft.
2. Only Word and PDF documents should be called "documents".  
     a. Excel files are called "spreadsheets",
     b. PowerPoint files "presentations", and 
     c. Visio files are called "drawings"

**Comment by lynelal** [comment]
Change [Accessible document guides: Office 365](https://a11y.canada.ca/en/guides/office365/)
To [Accessible content guides: Microsoft 365](https://a11y.canada.ca/en/guides/office365/)

and

Change [Accessible document guides: Office 2016](https://a11y.canada.ca/en/guides/office2016/)
To [Accessible content guides: Office 2016](https://a11y.canada.ca/en/guides/office2016/)

**Comment by lynelal** [comment]
Correction for Excel

Excel (.xlsx) files are not "Spreadsheets", they are "Workbooks".

**Comment by lynelal** [comment]
Here is my source for the Visio file type

[Introduction to the Visio file format (.vsdx) | Microsoft Learn](https://learn.microsoft.com/en-us/office/client-developer/visio/introduction-to-the-visio-file-formatvsdx)

**Comment by lynelal** [comment]
Here is a full recap:

### On this English page 
[How to create accessible documents in Office 365 - Digital Accessibility Toolkit / Sharing space (canada.ca)](https://a11y.canada.ca/en/guides/office365/)

Change the title
From : [How to create accessible documents in Office 365 - Digital Accessibility Toolkit / Sharing space (canada.ca)](https://a11y.canada.ca/en/guides/office365/)
To: [How to create accessible content in Microsoft 365 - Digital Accessibility Toolkit / Sharing space (canada.ca)](https://a11y.canada.ca/en/guides/office365/)
Note: this text is on the page in two locations

Change text: [Accessible PowerPoint documents]
To: [Accessible PowerPoint presentations]

Change: [Accessible Excel documents]
To: [Accessible Excel workbooks]
Source: Search for .xlsx on this page [File format reference for Word, Excel, and PowerPoint - Deploy Office | Microsoft Learn](https://learn.microsoft.com/en-us/DeployOffice/compat/office-file-format-reference)

Change: [Accessible Visio diagrams]
To [Accessible Visio drawings]
Source: Search for .vsdx on [Introduction to the Visio file format (.vsdx) | Microsoft Learn](https://learn.microsoft.com/en-us/office/client-developer/visio/introduction-to-the-visio-file-formatvsdx)

### On this French page 
[Comment créer des documents accessibles dans Office 365 - Boîte à outils d'accessibilité numérique / Espace de partage (canada.ca)](https://a11y.canada.ca/fr/guides/office365/)

Change the Title
From: [Comment créer des documents accessibles dans Office 365 - Boîte à outils d'accessibilité numérique / Espace de partage (canada.ca)](https://a11y.canada.ca/fr/guides/office365/)
To: [Comment créer du contenu accessible dans Microsoft 365 - Boîte à outils d'accessibilité numérique / Espace de partage (canada.ca)](https://a11y.canada.ca/fr/guides/office365/)

Change: [Comment créer des documents accessibles dans Office 365] 
To: [Comment créer du contenu accessible dans Microsoft 365]
Note: this text is in in two locations

Change: [Documents PowerPoint accessibles](https://a11y.canada.ca/fr/guides/office365/accessible-powerpoint-documents-365)
To: [Présentations PowerPoint accessibles](https://a11y.canada.ca/fr/guides/office365/accessible-powerpoint-presentations-365)

Change: [Documents Excel accessibles]
To: [Classeurs Excel accessibles]
Source: Search for .xlsx on this page [Référence des formats de fichier pour Word, Excel et PowerPoint - Deploy Office | Microsoft Learn](https://learn.microsoft.com/fr-fr/DeployOffice/compat/office-file-format-reference)

Change: [Diagrammes Visio accessibles]
To [Dessins Visio accessibles]
Source: Search for .vsdx on [Présentation du format de fichier Visio (.vsdx) | Microsoft Learn](https://learn.microsoft.com/fr-fr/office/client-developer/visio/introduction-to-the-visio-file-formatvsdx)

**Comment by lynelal** [comment]
![a11y canada ca-en-guides](https://user-images.githubusercontent.com/106971563/221247386-b409a5e5-55ab-4814-ac33-41509eb9c964.png)

**Comment by lynelal** [comment]
![a11y canada ca-en-guides](https://user-images.githubusercontent.com/106971563/221249949-9e8a39d4-4802-4146-bca8-cbbd6d3dc6ac.png)

**Comment by lynelal** [comment]
![a11y canada ca-en-guides](https://user-images.githubusercontent.com/106971563/221251048-d4136ff7-3708-4f41-8172-765ba47da349.png)

**Comment by lynelal** [comment]
![a11y canada ca-fr-guides](https://user-images.githubusercontent.com/106971563/221252883-d662fe5b-e0d7-461f-8a28-d21e1ed0969f.png)

**Comment by kimviens** [comment]
I would recommend using the word "document" rather than file. File can mean folder and we are not talking about folders in this context. How about "Microsoft Office Documents" instead?

**Comment by lynelal** [comment]
Yes, that works

**Comment by shawnthompson** [comment]
@lynelal is this still an issue with all the changes we did during the launch in December?

- [How to create accessible documents in Microsoft 365](https://a11y.canada.ca/en/how-to-create-accessible-documents-in-microsoft-365/)
- [How to create accessible documents in Office 2016](https://a11y.canada.ca/en/how-to-create-accessible-documents-in-office-2016/)

**Comment by lynelal** [comment]
Unclassified | Non classifié

Nope
