### ISSUE TITLE
Digital accessibility toolkit - How to create accessible documents

### ISSUE THREAD

**Issue by lynelal** [gc-da11yn/gc-da11yn.github.io#276]
### What page is the change request for? Please supply the URI.

https://a11y.canada.ca/en/guides/office365/

### Approval needed?

None

### Who shall do the work?

- [ ] I will do it, I want to contribute
- [X] I am asking for someone else to please do the work

### Additional context

In the "Additional resources" at the bottom of https://a11y.canada.ca/en/guides/office365/

Please replace [Microsoft – "Make your Word documents accessible"](https://support.office.com/en-ie/article/make-your-word-documents-accessible-to-people-with-disabilities-d9bf3683-87ac-47ea-b91a-78dcacb3c66d)

With:
- [Microsoft – "Make your content accessible to everyone"](https://support.microsoft.com/en-us/office/make-your-content-accessible-to-everyone-ecab0fcf-d143-4fe8-a2ff-6cd596bddc6d)

But keep [Microsoft – "Make your Word documents accessible"](https://support.office.com/en-ie/article/make-your-word-documents-accessible-to-people-with-disabilities-d9bf3683-87ac-47ea-b91a-78dcacb3c66d) 
as an "Additional resources" on this page: https://a11y.canada.ca/en/guides/office365/accessible-word-documents-365/

**Comment by shawnthompson** [comment]
@lynelal should we be adding it to the French version as well?

**Comment by lynelal** [comment]
Yes, also change in the French version

From [Microsoft – « Rendre vos documents Word accessibles aux personnes atteintes de handicaps »] (https://support.microsoft.com/fr-fr/office/rendre-vos-documents-word-accessibles-aux-personnes-atteintes-d-un-handicap-d9bf3683-87ac-47ea-b91a-78dcacb3c66d)

To [Microsoft - « Rendre votre contenu accessible à tous »] (https://support.microsoft.com/fr-fr/office/rendre-votre-contenu-accessible-%C3%A0-tous-ecab0fcf-d143-4fe8-a2ff-6cd596bddc6d)

**Comment by kellyanne-lecuyer** [comment]
@lynelal 

In this page [How to create accessible documents in Office 365](https://a11y.canada.ca/en/guides/office365/), the 2nd link is the same as the 1st link of this page [Accessible Word documents](https://a11y.canada.ca/en/guides/office365/accessible-word-documents-365/) but they just have a different title on DAT project. 

Which version of the title do you want me to keep?

**Comment by lynelal** [comment]
I'm sorry I don't understand what you are saying.

Can you call me? 613-799-7329

Lyne Lalonde
Technical Writer
On contract with Shared Services
