### ISSUE TITLE
[FEATURE] Add IDs to headings so that we can link to the heading/section directly

### ISSUE THREAD

**Issue by kimviens** [gc-da11yn/gc-da11yn.github.io#288]
### Is your feature request related to a problem? Please describe.

I would like to link to specific sections. To do that, I look into the code, grab the ID and I add it to the URL like this: http://mywebsite.com#headingID

### Describe the solution you'd like

Please add IDs to the headings so that I can create direct links.

### Who shall do the work?

- [X] I will do it, I want to contribute
- [X] I am asking for someone else to please do the work

### Timeline

No, as soon as possible but not a fire emergency

**Comment by NoahGresser** [comment]
I tried looking into if/how Markdown/eleventy can do this.
According to this [Markdown Extended Syntax Guide ](https://www.markdownguide.org/extended-syntax/#heading-ids) I found, it depends on the Markdown processors whether it support custom IDs for headings or automatically add them.
With eleventy, I found a [thread on the eleventy github repository](https://github.com/11ty/eleventy/issues/1593) from 2021 asking for a way to do it natively. Near the end of the thread someone had created an "[11ty plugin for adding ids to html headings and other elements](https://www.npmjs.com/package/@orchidjs/eleventy-plugin-ids)".

**Comment by shawnthompson** [comment]
I'd like this to be done automatically using the [markdown-it-anchor - npm](https://www.npmjs.com/package/markdown-it-anchor) plugin. 

We would need to convert all pages to markdown eventually and ensure it would work with headings that have French accents (or special characters) in them.

Your mission, should you choose to accept it, would be to setting up the plugin in the project and make sure it works with French headings. 

Second would be to open an new issue to convert all pages to markdown, using as little of HTML as possible.
