### ISSUE TITLE
[CHANGE] ICT Accessibility Requirements: Cleanup code

### ISSUE THREAD

**Issue by shawnthompson** [gc-da11yn/gc-da11yn.github.io#298]
### What page is the change request for? Please supply the URI.

https://a11y.canada.ca/en/guides/ict-requirements/

### Approval needed?

None

### Who shall do the work?

- [ ] I will do it, I want to contribute
- [X] I am asking for someone else to please do the work

## Clean up code on this page.

The following elements should be all in one line:

- `p`
- `li`
- `h#`
- `figcaption`

Pretty much any HTML element with text in it, should not be wrapped by a return / line break.

## Add captions to images and link references

**Was:** 

```
<figure class="col-lg-6">
<figcaption class="h4">Figure 1: Relationship between minimum character height and maximum design viewing distance</figcaption>
<img class="img-responsive" src="../../../img/requirements/image1.png" alt="Diagram illustrating the linear relationship of the text 5.1.4 Functionality closed to text enlargement">
</figure>
```

**Change to:**

```
<figure class="col-lg-6">
<figcaption class="h4">Figure 1: Relationship between minimum character height and maximum design viewing distance</figcaption>
<img class="img-responsive" src="../../../img/requirements/image1.png" alt="">
<p>Diagram illustrating the linear relationship of the text <a href="#5.1.4">5.1.4 Functionality</a> closed to text enlargement</p>
</figure>
```

Making sure you add an `id` to the referenced point to link back any references in the alt text.

```
<p id="5.1.4"><strong>5.1.4 Functionality closed to text enlargement</strong></p>
```

Apply the same changes to the French page.

**Comment by shawnthompson** [comment]
The wording in the `alt` text can not be changed because it's from the EN 301 / Ernie standards.

**Comment by NoahGresser** [comment]
the proposed change to make alt attribute empty causes the image to be ignored by Assistive technologies. As a result, the screen readers completely ignore the images and only read the description. The existence of the image should still be conveyed to AT users. Could we keep the alt text as it is, but also text below that just says something like:
`<p>Figured referenced by <a href="#5.1.4">5.1.4 Functionality closed to text enlargement</a></p>`
?

**Comment by shawnthompson** [comment]
Thanks @NoahGresser for bringing this to my attention. You are right and after testing different options of this with different screen reader, which all work differently. I've decided to leave the `alt` values and just add links to the references below the images, which would repeat some of the text but definitely our best option.

Suggestions:

``` html
<figure>
	<figcaption>Unobstructed side reach</figcaption>
	<img src="https://a11y.canada.ca/img/requirements/image6.png" alt="A diagram illustrating the content of the text 8.3.3.2 Unobstructed low side reach. Person in a wheelchair reaching to the side.">
 	<p>Related content:<p> 
	<ul>
		<li><a href="#fig6def">8.3.3.2 Unobstructed low side reach</a></li>
	</ul>
</figure>
```

**Comment by shawnthompson** [comment]
Closed by accident

**Comment by shawnthompson** [comment]
Being worked on in https://github.com/gc-da11yn/gc-da11yn.github.io/pull/317
