### ISSUE TITLE
[SMALL CHANGE] Tools and Resources looks ugly

### ISSUE THREAD

**Issue by kimviens** [gc-da11yn/gc-da11yn.github.io#302]
### What page is the change request for? Please supply the URI.

https://a11y.canada.ca/en/guides/

### Approval needed?

None

### Who shall do the work?

- [ ] I will do it, I want to contribute
- [X] I am asking for someone else to please do the work

### Additional context

Is it possible to fix the big column of the procurement section on the tools and resources page? It makes me uncomfortable to see the small User Experience section next to the big Procurement section. Can we at least put procurement on the left side?

**Comment by shawnthompson** [comment]
This is being reworked for the launch at the end of May. 

Stay tuned for changes.
