### ISSUE TITLE
[MODIFICATION] Brève description de la page

### ISSUE THREAD

**Issue by lynelal** [gc-da11yn/gc-da11yn.github.io#304]
### Quelle page fait l'objet de la demande de modification ? Veuillez fournir l'URI.

https://a11y.canada.ca/fr/guides/design-accessible-services/

### Approbation nécessaire ?

Oui, j'ai besoin d'approuver cette demande avant que le changement ne soit effectif

### Oui, veuillez envoyer une demande à la personne suivante?

lyne.lalonde@ssc-spc.gc.ca

### Qui devrait travailler à développer ce changement ?

- [ ] Je vais le faire, je veux contribuer
- [X] Je demande à quelqu'un d'autre de faire le travail s’il vous plaît

### Contexte additionnel
see Word document tracked changes in the comment below

**Comment by lynelal** [comment]
[Principes de conception pour des services accessibles.docx](https://github.com/gc-da11yn/gc-da11yn.github.io/files/11544084/Principes.de.conception.pour.des.services.accessibles.docx)

**Comment by shawnthompson** [comment]
Changes made and will go live on Sunday December 3, 2024.

Have a look on the preview server:

- [En cours de développement - Principes de conception pour les utilisateurs avec handicap cognitif - Boîte à outils d'accessibilité numérique / Espace de partage](https://deploy-preview-335--a11ycanada.netlify.app/fr/principes-de-conception-pour-les-utilisateurs-avec-handicap-cognitif/)
- [En cours de développement - Concevoir pour les utilisateurs de revues d’écran - Boîte à outils d'accessibilité numérique / Espace de partage](https://deploy-preview-335--a11ycanada.netlify.app/fr/concevoir-pour-les-utilisateurs-de-revues-d-ecran/)
