### ISSUE TITLE
New Resource for creating accessible emails?

### ISSUE THREAD

**Issue by PlauntJ** [gc-da11yn/gc-da11yn.github.io#307]
### Décrivez la solution que vous aimeriez voir

Hi folks, I've noticed on https://a11y.canada.ca/en/ that there is no resource for creating accessible emails. 

Here at Statistics Canada we've developed a great short and tidy resource for making accessible emails (available in EN/FR) which we'd be happy to share for A11Y.canada.ca to post. 

If you're interested, please let me know at jeremy.plaunt@statcan.gc.ca - happy to provide you with original documents.

Thanks so much - merci beaucoup!

### Qui devrait travailler à développer ce changement ?

- [x] Je vais le faire, je veux contribuer
- [ ] Je demande à quelqu'un d'autre de faire le travail s’il vous plaît

**Comment by kimviens** [comment]
I think we have new documentation for accessible documents coming out soon. I will check if accessible emails are a part of it. But I think in the meantime my recommendation would be to create the email in Word and copy paste into Outlook.

**Comment by kimviens** [comment]
@PlauntJ Oups, I misread your text. I see that you already have a guide. Great! Let me double check to see if we already have some content too. If we do, we could work together to merge content and if not I'll get permission to code your document into the digital accessibility toolkit.

**Comment by JulieBB23** [comment]
Updated the content for [accessible email](https://deploy-preview-335--a11ycanada.netlify.app/en/making-accessible-emails/)
