### ISSUE TITLE
[BROKEN LINK] Dessins Visio accessibles

### ISSUE THREAD

**Issue by lynelal** [gc-da11yn/gc-da11yn.github.io#309]
### What page is the broken link found on? Please supply the URL.

https://a11y.canada.ca/fr/guides/office365/

### Link text of the link

Dessins Visio accessibles

### Approval needed?

None

### Who shall do the work?

- [ ] I will do it, I want to contribute
- [X] I am asking for someone else to please do the work

### Timeline

It's up to you, but this is an easy quick fix

### Additional context

You only need to fix the 'Dessins Visio accessibles' link address on this page https://a11y.canada.ca/fr/guides/office365/ 
Note: all the other French pages work correctly.

**Change link address:**
- From: https://a11y.canada.ca/fr/guides/office365/accessible-visio-documents-365
- To: https://a11y.canada.ca/fr/guides/office365/accessible-visio-diagrams-365

**Comment by shawnthompson** [comment]
Fixed, thanks @lynelal
