### ISSUE TITLE
[CHANGE] Update to footer to GCWeb v12.6.1

### ISSUE THREAD

**Issue by shawnthompson** [gc-da11yn/gc-da11yn.github.io#313]
### Approval needed?

None

### Who shall do the work?

- [ ] I will do it, I want to contribute
- [X] I am asking for someone else to please do the work

### Additional context

Update the footer as per the email from principle publisher

- [Site footer](https://wet-boew.github.io/GCWeb/sites/footers/footers-en.html): Added contextual footer band and applied other changes to global footer.

``` html
<footer id="wb-info">
	<h2 class="wb-inv">About this site</h2>
<div class="gc-contextual">
		<div class="container">
			<nav>
				<h3>[Contextual footer header]</h3>
				<ul class="list-col-xs-1 list-col-sm-2 list-col-md-3"><li><a href="http://canada.ca/en">Contextual link 1</a></li><li><a href="http://canada.ca/en">Contextual link 2</a></li><li><a href="http://canada.ca/en">Contextual link 3</a></li></ul>
			</nav>
		</div>
	</div>

	<div class="gc-main-footer">
		<div class="container">
			<nav>
				<h3>Government of Canada</h3>
				<ul class="list-col-xs-1 list-col-sm-2 list-col-md-3"><li><a href="https://www.canada.ca/en/contact.html">All contacts</a></li>
					<li><a href="https://www.canada.ca/en/government/dept.html">Departments and agencies</a></li>
					<li><a href="https://www.canada.ca/en/government/system.html">About government</a></li></ul>
				<h4><span class="wb-inv">Themes and topics</span></h4>
				<ul class="list-unstyled colcount-sm-2 colcount-md-3"><li><a href="https://www.canada.ca/en/services/jobs.html">Jobs</a></li>
					<li><a href="https://www.canada.ca/en/services/immigration-citizenship.html">Immigration and citizenship</a></li>
					<li><a href="https://travel.gc.ca/">Travel and tourism</a></li>
					<li><a href="https://www.canada.ca/en/services/business.html">Business</a></li>
					<li><a href="https://www.canada.ca/en/services/benefits.html">Benefits</a></li>
					<li><a href="https://www.canada.ca/en/services/health.html">Health</a></li>
					<li><a href="https://www.canada.ca/en/services/taxes.html">Taxes</a></li>
					<li><a href="https://www.canada.ca/en/services/environment.html">Environment and natural resources</a></li>
					<li><a href="https://www.canada.ca/en/services/defence.html">National security and defence</a></li>
					<li><a href="https://www.canada.ca/en/services/culture.html">Culture, history and sport</a></li>
					<li><a href="https://www.canada.ca/en/services/policing.html">Policing, justice and emergencies</a></li>
					<li><a href="https://www.canada.ca/en/services/transport.html">Transport and infrastructure</a></li>
					<li><a href="https://international.gc.ca/world-monde/index.aspx?lang=eng">Canada and the world</a></li>
					<li><a href="https://www.canada.ca/en/services/finance.html">Money and finance</a></li>
					<li><a href="https://www.canada.ca/en/services/science.html">Science and innovation</a></li>
					<li><a href="https://www.canada.ca/en/services/indigenous-peoples.html">Indigenous peoples</a></li>
					<li><a href="https://www.canada.ca/en/services/veterans-military.html">Veterans and military</a></li>
					<li><a href="https://www.canada.ca/en/services/youth.html">Youth</a></li></ul>
			</nav>
		</div>
	</div>

	<div class="gc-sub-footer">
		<div class="container d-flex align-items-center">
			<nav>
				<h3 class="wb-inv">Government of Canada Corporate</h3>
				<ul>
					<li><a href="https://www.canada.ca/en/social.html">Social media</a></li>
					<li><a href="https://www.canada.ca/en/mobile.html">Mobile applications</a></li>
					<li><a href="https://www.canada.ca/en/government/about.html">About Canada.ca</a></li><li><a href="https://www.canada.ca/en/transparency/terms.html">Terms and conditions</a></li>
					<li><a href="https://www.canada.ca/en/transparency/privacy.html">Privacy</a></li></ul>
			</nav>
			<div class="wtrmrk align-self-end">
				<img src="https://wet-boew.github.io/themes-dist/GCWeb/GCWeb/assets/wmms-blk.svg" alt="Symbol of the Government of Canada" />
			</div>
		</div>
	</div>
</footer>
```

**Comment by shawnthompson** [comment]
## Contextual footer

Header: Digital Accessibility Toolkit

List of links:

- Contact the Digital Accessibility Toolkit (page not created)
- [Accessibility in Government of Canada](https://a11y.canada.ca/en/about/organizations/)
- Accessibility in your role (page not created)

![Image](https://github.com/gc-da11yn/gc-da11yn.github.io/assets/2575266/c6f72248-d4b7-44ae-99d2-e967b0e40ea1)

**Comment by shawnthompson** [comment]
@JulieBB23 @emmatseng-ux @oyinR

Can we get the French translations for the Contextual footer, please?

**Comment by emmatseng-ux** [comment]
Hey Shawn a few updates for the Github footer, from Melissa and Julie, here are the updated translations:
"Code source (en anglais seulement)" 
"Discussions (en anglais seulement)"
![image](https://github.com/gc-da11yn/gc-da11yn.github.io/assets/136023479/8c1e275e-0cf1-47e0-8928-578755664d8a)

**Comment by acev0010** [comment]
Hello, I'm Isabel and I'm updating the changes for the footer. Thank you for the update.

I'm only waiting for the French translation of the contextual footer when possible, please:

> ## Contextual footer
> Header: Digital Accessibility Toolkit
> 
> List of links:
> 
> * Contact the Digital Accessibility Toolkit (page not created)
> * [Accessibility in Government of Canada](https://a11y.canada.ca/en/about/organizations/)
> * Accessibility in your role (page not created)
> 
> ![Image](https://user-images.githubusercontent.com/2575266/256243698-c6f72248-d4b7-44ae-99d2-e967b0e40ea1.png)

**Comment by emmatseng-ux** [comment]
Hey Isabel, I know you're working on the contextual footer but the Github footer will also need to be updated by someone on the team. Is this thread a suitable place to store that information?

As for the contextual footer, here is the translation. Thanks so much!

- Contact the Digital Accessibility Toolkit (page not created) / Contacter la Boîte à outils d'accessibilité numérique
- [Accessibility in Government of Canada](https://a11y.canada.ca/en/about/organizations/) / Accessibilité au gouvernement du Canada 
- Accessibility in your role (page not created) / Accessibilité par rôle

**Comment by acev0010** [comment]
Thank you for the translation. As for the GitHub Footer, I can take care of it. I will make a separate commit for it and wait for Shawn to decide if we want to keep it in the same pull request or separate. He is away for a few weeks so he might not answer right away, but I'll leave everything ready so we just need the approval to wrap this up.

**Comment by emmatseng-ux** [comment]
Amazing, thanks so much for your help Isabel! Let me know if there's anything else I can support you with.

**Comment by acev0010** [comment]
You're welcome! I made two separate pull requests, one for the footer #324  and one for the GitHub footer #326 

I would like to note that the GitHub footer doesn't look exactly like the screenshot you provided, since the ''(en anglais seulement)'' is in the same line as ''Code source'' instead of one on top of the other. I wasn't sure if it was due to a reflow issue so if you think it's a mistake then let me know in the pull request #326

**Comment by shawnthompson** [comment]
> Hey Shawn a few updates for the Github footer, from Melissa and Julie, here are the updated translations:
> "Code source (en anglais seulement)"
> "Discussions (en anglais seulement)"
> ![image](https://user-images.githubusercontent.com/136023479/257549526-8c1e275e-0cf1-47e0-8928-578755664d8a.png)

I'll update this in my version: [creates grid for contribute section by shawnthompson · Pull Request #308 · gc-da11yn/gc-da11yn.github.io](https://github.com/gc-da11yn/gc-da11yn.github.io/pull/308) for the contribute section of the footer.
