### ISSUE TITLE
[CHANGE] Split that page into 6 pages

### ISSUE THREAD

**Issue by JulieBB23** [gc-da11yn/gc-da11yn.github.io#355]
### What page is the change request for? Please supply the URI.

https://a11y.canada.ca/en/guides/design-accessible-services/
https://a11y.canada.ca/fr/guides/design-accessible-services/

### Approval needed?

Yes, I need to approve this request before change goes live

### Yes, please send a request to the following person?

julie.belisleboutet@csps-efpc.gc.ca

### Who shall do the work?

- [ ] I will do it, I want to contribute
- [X] I am asking for someone else to please do the work

### Additional context
The same task will need to be done for the French.

The content on that page need to be split into 6 pages as followed: 

- Designing for users on the autistic spectrum
- Design principles for users with cognitive disabilities
- Designing for users who are deaf or hard of hearing
- Designing for users with low vision
- Designing for users with physical or motor disabilities
- Designing for users of screen readers

The content on the new page should be the HTML version of the do's and don't plus the link to the PDF poster.

**Comment by shawnthompson** [comment]
@JulieBB23 each of these pages are going to need a description.

**Comment by shawnthompson** [comment]
Here is the staging link for the section:
[In development - Designing accessible services - Digital Accessibility Toolkit / Sharing space](https://deploy-preview-388--a11ycanada.netlify.app/en/designing-accessible-services/)

**Comment by JulieBB23** [comment]
@bsouster Do you think you could help to provide description for each page?

**Comment by martynka** [comment]
> @bsouster Do you think you could help to provide description for each page?

@JulieBB23 and @bsouster I will check with Emily, she was working on descriptions to some pages. I believe Shawn has shared a list with her.

**Comment by shawnthompson** [comment]
Thie descriptions have been done:

[In development - Designing accessible services - Digital Accessibility Toolkit / Sharing space](https://deploy-preview-335--a11ycanada.netlify.app/en/designing-accessible-services/)
