### ISSUE TITLE
Petit problème avec la page en Français pour les exigences en matière de technologies de l’information et des communications (TIC) accessibles

### ISSUE THREAD

**Issue by kimviens** [gc-da11yn/gc-da11yn.github.io#361]
### Description du bogue

**Pour le reproduire**
Étapes pour reproduire le problème :
1. Allez à ["Exigences en matière de technologies de l’information et des communications (TIC) accessibles"](https://a11y.canada.ca/fr/guides/ict-requirements/)
2. Voir "4.2.10 Les TIC fournissent des fonctions et/ou une présentation qui simplifient la compréhension, le fonctionnement et l’utilisation. Ceci est essentiel pour les utilisateurs ayant des capacités cognitives, linguistiques ou d’apprentissage limitées et aussi bénéfique à plusieurs autres dans différentes situations." et compare avec la version en anglais.

**Scénario attendu**
Cela ne reflète pas la même chose que la version anglaise.

**Qui devrait travailler à corriger ce problem?**
Si j'ai le temps je peux réparer le problème.

**Comment by shawnthompson** [comment]
@kimviens Can you check with @benjamin-rolleman  to make sure this isn't the file that's outputted from the Wizard?

**Comment by shawnthompson** [comment]
After comparing against the Word document on the page, it was missing text.

It should be as follows:

<p><strong>4.2.10 Utilisation avec des capacités cognitives, linguistiques ou d’apprentissage limitées:</strong> Les TIC fournissent des fonctions et/ou une présentation qui simplifient la compréhension, le fonctionnement et l’utilisation. Ceci est essentiel pour les utilisateurs ayant des capacités cognitives, linguistiques ou d’apprentissage limitées et aussi bénéfique à plusieurs autres dans différentes situations.</p>

@kimviens Please confirm that is the different you were noticing.

Code for update:

``` html
<p><strong>4.2.10 Utilisation avec des capacités cognitives, linguistiques ou d’apprentissage limitées:</strong> Les TIC fournissent des fonctions et/ou une présentation qui simplifient la compréhension, le fonctionnement et l’utilisation. Ceci est essentiel pour les utilisateurs ayant des capacités cognitives, linguistiques ou d’apprentissage limitées et aussi bénéfique à plusieurs autres dans différentes situations.</p>
```

**Comment by shawnthompson** [comment]
Have a look @kimviens and let me know if the change is what you requested.

[En cours de développement - Exigences en matière de technologies de l’information et des communications (TIC) accessibles - Boîte à outils d'accessibilité numérique / Espace de partage](https://deploy-preview-439--a11ycanada.netlify.app/fr/exigences-en-matiere-de-technologies-de-l-information-et-des-communications-tic-accessibles/)

Merci 👍
