### ISSUE TITLE
[CHANGE] Update Autism French PDF.

### ISSUE THREAD

**Issue by nricherbrule** [gc-da11yn/gc-da11yn.github.io#400]
### What page is the change request for? Please supply the URI.

https://a11y.canada.ca/docs/posters/SpectreAutistique-fr_2023.pdf

### Approval needed?

None

### Who shall do the work?

- [ ] I will do it, I want to contribute
- [ ] I am asking for someone else to please do the work

### Timeline

Asap

### Additional context

[SpectreAutistique-fr_2023.pdf](https://github.com/gc-da11yn/gc-da11yn.github.io/files/13206034/SpectreAutistique-fr_2023.pdf)

**Comment by shawnthompson** [comment]
Updated:

[SpectreAutistique-fr_2023.pdf](https://deploy-preview-335--a11ycanada.netlify.app/docs/posters/SpectreAutistique-fr_2023.pdf)
