### ISSUE TITLE
[CHANGE] New contet under : Design a course

### ISSUE THREAD

**Issue by JulieBB23** [gc-da11yn/gc-da11yn.github.io#408]
### What page is the change request for? Please supply the URI.

https://deploy-preview-335--a11ycanada.netlify.app/en/design-a-course/

### Approval needed?

Yes, I need to approve this request before change goes live

### Who shall do the work?

- [ ] I will do it, I want to contribute
- [X] I am asking for someone else to please do the work

### Additional context

Please see the note for the Developer, for the layout, as it is a Do's and don't we need 2 column (Div) so users can see and compare the good and the bad at the same time.
 
[dos_dont-eng.docx](https://github.com/gc-da11yn/gc-da11yn.github.io/files/13268914/dos_dont-eng.docx)
[dos_dont-fr.docx](https://github.com/gc-da11yn/gc-da11yn.github.io/files/13268911/dos_dont-fr.docx)

 <html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/jbelisle/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/jbelisle/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/jbelisle/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-CA style='tab-interval:.5in;word-wrap:break-word'>

Category | Sub-category | Subject | Tags
-- | -- | -- | --
How to’s | Design a   course | howTos | designCourse

</body>

</html>

**Comment by JulieBB23** [comment]
Is it possible to do the layout in two column please.

**Comment by shawnthompson** [comment]
Done

[In development - Do’s and Don’ts for developing online courses - Digital Accessibility Toolkit / Sharing space](https://deploy-preview-335--a11ycanada.netlify.app/en/do-s-and-don-ts-for-developing-online-courses/)
