### ISSUE TITLE
[CHANGE] Digital Accessibility Toolkit Description

### ISSUE THREAD

**Issue by lynelal** [gc-da11yn/gc-da11yn.github.io#418]
### What page is the change request for? Please supply the URI.

https://deploy-preview-335--a11ycanada.netlify.app/en/

### Approval needed?

None

### Who shall do the work?

- [ ] I will do it, I want to contribute
- [X] I am asking for someone else to please do the work

### Additional context

This is a recommendation.  Please have the content author review the change and approve it prior to editing.

Why make the change: Plain language
•	Having both ‘learning materials’ and ‘learn’ in same sentence is redundant 
•	Sentence is too long
•	‘implement accessibility in your digital project’ is awkward and confusing phrasing
•	Implement is a long word

**Change text from** 
‘We offer a variety of learning materials and resources to help you learn and implement accessibility in your digital projects.’ 
**To** 
‘We offer a variety of learning materials and resources to help you deliver accessible digital projects.’ 

French:
**From:**
'Nous offrons une variété de matériel d'apprentissage et de ressources pour vous aider à apprendre et à mettre en œuvre l'accessibilité dans vos projets numériques.' 
**To:**
'Nous offrons une variété de matériel d'apprentissage et de ressources pour vous aider à réaliser des projets numériques accessibles.' 
<img width="288" alt="Digital Accessibility Toolkit description" src="https://github.com/gc-da11yn/gc-da11yn.github.io/assets/106971563/1b32edff-9627-4420-9787-9e481aac3ea2">

**Comment by lynelal** [comment]
<img width="288" alt="Digital Accessibility Toolkit description" src="https://github.com/gc-da11yn/gc-da11yn.github.io/assets/106971563/431a9168-b3cc-445b-9613-adf0faa4c5fe">

**Comment by shawnthompson** [comment]
@JulieBB23 thoughts about this change?

**Comment by JulieBB23** [comment]
All good, please go ahead with the changes. Thanks @lynelal

**Comment by lynelal** [comment]
@JulieBB23 You're welcome.

**Comment by shawnthompson** [comment]
Over to you @DhruvPatel2502. Please make this change.

**Comment by JulieBB23** [comment]
description has been done.
