### ISSUE TITLE
[CHANGE] Accessibility Fundamentals descriptions

### ISSUE THREAD

**Issue by lynelal** [gc-da11yn/gc-da11yn.github.io#419]
### What page is the change request for? Please supply the URI.

https://deploy-preview-335--a11ycanada.netlify.app/en/

### Approval needed?

None

### Who shall do the work?

- [ ] I will do it, I want to contribute
- [X] I am asking for someone else to please do the work

### Additional context

This is a recommendation. Please have the content author review the change and approve it prior to editing.

Why make the change: Plain language
• Long and awkward sentence.
• As a rule, any sentence with 'that' needs to be re-written.
• Difficult to understand.
• Avoid sentences that need a comma (e.g. before "while").

Change text from
‘Discover the accessibility principles behind creating digital products and services that remove barriers for people living with disabilities while ensuring ease of use for all.’ Flesch-Kincaid 19.2
To
‘Discover the principles behind accessible digital products and services. These principles remove barriers for people living with disabilities and ensures ease of use for all.’ Flesh-Kincaid 12.9

French:
From:
'Découvrez les principes d'accessibilité qui guident la création de produits et de services numériques qui éliminent les obstacles pour les personnes handicapées tout en assurant une facilité d'utilisation pour tous.'  Flesch-Kincaid 19.8
To:
'Découvrez les principes qui guident l'accessibilité des produits et services numériques. Ces principes éliminent les obstacles pour les personnes en situation de handicap et facilitent l’utilisation pour tous.' Flesh-Kincaid 12.7

**Comment by shawnthompson** [comment]
@JulieBB23 thoughts on this change?

**Comment by JulieBB23** [comment]
All good please go ahead. Thanks @lynelal

**Comment by shawnthompson** [comment]
Changes made:

- [En cours de développement - Boîte à outils d'accessibilité numérique - Boîte à outils d'accessibilité numérique / Espace de partage](https://deploy-preview-437--a11ycanada.netlify.app/fr/)
- [In development - Digital Accessibility Toolkit - Digital Accessibility Toolkit / Sharing space](https://deploy-preview-437--a11ycanada.netlify.app/en/)

**Comment by lynelal** [comment]
@shawnthompson  Thank you so much.  Looks great!
