### ISSUE TITLE
[BUG] Markdown Headings IDs issue

### ISSUE THREAD

**Issue by acev0010** [gc-da11yn/gc-da11yn.github.io#502]
### Describe the bug

**Description of the issue**

Using special characters (specifically a colon) on the heading of the markdown files will result in the ID not being translated properly and making skip links unusable. 

A temporary solution for this is by adding the id on the side like this: "`## Tool: WAVE Browser Extensions {#tool-wave-browser-extensions}`".

It might be related to the plugin we use, "markdown-it-anchor".

**Expected behaviour**
Headings with special characters should be transformed properly.

For example: `"## Tool: WAVE Browser Extensions"`
Should be: `"<h2 id="tool-wave-browser-extensions" tabindex="-1">Tool: WAVE Browser Extensions</h2>"`
instead, we get something like this: `"<h2 id="to^&$wave-browser-extensions" tabindex="-1">Tool: WAVE Browser Extensions</h2>"`

**Who shall do the work?**
[I will do it, I want to contribute] or [I am asking for someone else to please do the work]

### OS or Device: (e.g. iOS)

Desktop

### Browser (e.g. Chrome, Safari)

Chrome

**Comment by acev0010** [comment]
This seems to be a problem with markdown-it-anchor, I found this issue in their GitHub development project: 

https://github.com/valeriangalliat/markdown-it-anchor/issues/127

**Comment by shawnthompson** [comment]
I think you can add that code into the [.eleventy.js](https://github.com/gc-da11yn/gc-da11yn.github.io/blob/main/.eleventy.js#L7 ) in the `eleventyConfig` function
