### ISSUE TITLE
Disable pages while new content is written (EN and FR)

### ISSUE THREAD

**Issue by Syracopoulos** [gc-da11yn/gc-da11yn.github.io#530]
### What page is the change request for? Please supply the URI.

https://a11y.canada.ca/en/captioning-guidelines/

### Approval needed?

None

### Who shall do the work?

- [ ] I will do it, I want to contribute
- [X] I am asking for someone else to please do the work

### Additional context

Please disable the French and English Checklist pages as well, while we rewrite the content.
https://a11y.canada.ca/en/captioning-checklist/

**Comment by shawnthompson** [comment]
@JulieBB23, do you approve this message?

**Comment by JulieBB23** [comment]
@shawnthompson , approve please go ahead.

**Comment by Syracopoulos** [comment]
I am reviewing the new content today and will update when approved

**Comment by shawnthompson** [comment]
@Syracopoulos will be adding the updated content to this issue later today and we will update it instead of removing it first.

**Comment by Syracopoulos** [comment]
@shawnthompson I have to get the new content approved by the TF and Jeff or Brad and then translated. So it won't be coming today now. We should disable these pages in the meantime still.

**Comment by shawnthompson** [comment]
Removed pages. Will recreate when new content is ready.

https://deploy-preview-546--a11ycanada.netlify.app/en/captioning-guidelines/
https://deploy-preview-546--a11ycanada.netlify.app/fr/directives-pour-le-sous-titrage/
