### ISSUE TITLE
[CHANGE] All instances of "autistic spectrum" and "spectre autistique" should be changed to "autism spectrum" and "spectre de l'autisme", respectively

### ISSUE THREAD

**Issue by NoahGresser** [gc-da11yn/gc-da11yn.github.io#537]
### What page is the change request for? Please supply the URI.

https://a11y.canada.ca/en/designing-for-users-on-the-autistic-spectrum/index.html

### Approval needed?

None

### Who shall do the work?

- [ ] I will do it, I want to contribute
- [X] I am asking for someone else to please do the work

### Additional context

The terms "autistic spectrum" and "spectre autistique" are incorrect, they therefore need to be replaced with correct terminology "autism spectrum" and "spectre de l'autisme". 
Investigation needs to be done to determine all the instances of the incorrect terminology in the toolkit that need to be replaced. The currently known instances include:

1. On the page https://a11y.canada.ca/en/designing-for-users-on-the-autistic-spectrum/index.html:
- The page title "Designing for users on the **autistic spectrum** - Digital Accessibility Toolkit"
- The level 1 heading "Designing for users on the **autistic spectrum**"
- The page description "What to do - and what not to do - when designing for users on the **autistic spectrum**."
- The link text "Designing for users on the **autistic spectrum** (PDF, 47 KB)" to the PDF Poster
- (Potentially, assuming the URL is meant to match the page title as much as possible) The page URL "a11y.canada.ca/en/designing-for-users-on-the-**autistic-spectrum**/index.html" (this would also require updating the href for all links leading to this page)

2. On the page https://a11y.canada.ca/fr/concevoir-pour-les-utilisateurs-dans-le-spectre-autistique/index.html:
- The page title "Concevoir pour les utilisateurs dans le **spectre autistique** - Boîte à outils de l'accessibilité numérique"
- The level 1 heading "Concevoir pour les utilisateurs dans le **spectre autistique**"
- The page description "Ce qu'il faut faire - et ce qu'il ne faut pas faire - lors de la conception pour les utilisateurs du **spectre autistique**."
- The link text "Concevoir pour les utilisateurs dans le **spectre autistique** (PDF, 67 ko)" to the PDF Poster
- (Potentially, assuming the URL is meant to match the page title as much as possible) The page URL "a11y.canada.ca/fr/concevoir-pour-les-utilisateurs-dans-le-**spectre-autistique**/index.html" (this would also require updating the href for all links leading to this page)

3. On the PDF Poster https://a11y.canada.ca/docs/posters/AutismSpect-en_2023.pdf:
- The heading "Designing for users on the **autistic spectrum**"

4. On the PDF Poster https://a11y.canada.ca/docs/posters/SpectreAutistique-fr_2023.pdf:
- The heading "Concevoir pour les utilisateurs dans le **spectre autistique**"
- (Potentially) the file name "**SpectreAutistique**-fr_2023.pdf" (this would also require updating the href for all links leading to this PDF poster)

5. On the page https://a11y.canada.ca/en/designing-accessible-services/:
- The link text "Designing for users on the **autistic spectrum**" to the page listed above in this issue description as item 1
- The text "What to do - and what not to do - when designing for users on the **autistic spectrum**." below the link mentioned above

6. On the page https://a11y.canada.ca/fr/principes-de-conception-pour-des-services-accessibles/:
- The link text "Concevoir pour les utilisateurs dans le **spectre autistique**" to the page listed above in this issue description as item 2
- The text "Ce qu'il faut faire - et ce qu'il ne faut pas faire - lors de la conception pour les utilisateurs du **spectre autistique**." below the link mentioned above

7. On the page https://a11y.canada.ca/en/designing-accessible-services/:
- The link text "Designing for users on the **autistic spectrum** (HTML)" to the page listed above in this issue description as item 1
- The text "What to do - and what not to do - when designing for users on the **autistic spectrum**." below the link mentioned above
- The link text "Designing for users on the **autistic spectrum** (PDF, 47 KB)" to the PDF Poster

8. On the page https://a11y.canada.ca/fr/principes-de-conception-pour-des-services-accessibles/:
- The link text "Concevoir pour les utilisateurs dans le **spectre autistique** (HTML)" to the page listed above in this issue description as item 2
- The text "Ce qu'il faut faire - et ce qu'il ne faut pas faire - lors de la conception pour les utilisateurs du **spectre autistique**." below the link mentioned above
- The link text "Concevoir pour les utilisateurs dans le **spectre autistique** (PDF, 67 ko)" to the PDF Poster

**Comment by shawnthompson** [comment]
@NoahGresser Do you want to attempt to make this change yourself? I can help you with Github's online dev tools to make it happen.

**Comment by NoahGresser** [comment]
The preference of using identity-first language language applies to describing individuals on the spectrum, not the spectrum itself.  In fact, if you search the word "spectrum" on the Autistic Self Advocacy Network site you linked, you will only find examples of the term "autism spectrum", and no reference to "autistic spectrum".

It seems that the UK uses the term "Autistic Spectrum Condition (ASC)", while North America uses the term "Autistic Spectrum Disorder (ASD)" (such as in the definition from the DSM). This can be seen in already existing Canada.ca pages such as "[Autism: About, causes and co-occurring conditions - Canada.ca](https://www.canada.ca/en/public-health/services/diseases/autism-spectrum-disorder-asd.html)". 

I could understand a potential argument that instead of "Designing for users on the autism spectrum", the instances should be changed to "Designing for autistic users" (though I feel much less qualified to say which one would be better), but "autistic spectrum" is not terminology that we should be using.
