### ISSUE TITLE
Review of "Report a problem" button on https://a11y.canada.ca/

### ISSUE THREAD

**Issue by Syracopoulos** [gc-da11yn/gc-da11yn.github.io#552]
### What page is the change request for? Please supply the URI.

https://a11y.canada.ca/en/

### Approval needed?

None

### Who shall do the work?

- [ ] I will do it, I want to contribute
- [X] I am asking for someone else to please do the work

### Additional context

As per conversation in the DAIU meeting - please review the button on the Canada.ca template and investigate if it can be removed. It does not successfully resolve reported issues and it bugs Martyna :)

**Comment by shawnthompson** [comment]
Closed with #551
