### ISSUE TITLE
[CHANGE] Small copy change to  the Project de la Boîte à outils de l'accessibilité numérique - Boîte à outils de l'accessibilité numérique (canada.ca) page 

### ISSUE THREAD

**Issue by RM-1978** [gc-da11yn/gc-da11yn.github.io#555]
### What page is the change request for? Please supply the URI.

https://a11y.canada.ca/fr/project-de-la-boite-a-outils-de-l-accessibilite-numerique/

### Approval needed?

No

### Who shall do the work?

- [ ] I will do it, I want to contribute
- [X] I am asking for someone else to please do the work

### Timeline

As soon as possible.

### Additional context

Just writing to flag an important typo found by a colleague that should be addressed in the FR page title.
Please change the word **"project. "** to **"projet." ** We should address this as soon as possible.

**Comment by shawnthompson** [comment]
Thanks for reporting it @RM-1978 
Fixed in #556, just waiting on a review.
