### ISSUE TITLE
Edits to best practices for accessible virtual events 

### ISSUE THREAD

**Issue by Syracopoulos** [gc-da11yn/gc-da11yn.github.io#566]
### What page is the change request for? Please supply the URI.

https://a11y.canada.ca/en/best-practices-for-accessible-virtual-events/

### Approval needed?

None

### Who shall do the work?

- [ ] I will do it, I want to contribute
- [X] I am asking for someone else to please do the work

### Timeline

Must be updated before Feb 5 as the page is being promoted in SSC Gazette

### Additional context

[Best practices for accessible virtual events EN.docx](https://github.com/gc-da11yn/gc-da11yn.github.io/files/14114961/Best.practices.for.accessible.virtual.events.EN.docx)

**Comment by shawnthompson** [comment]
@Syracopoulos Are there changes to be done in the French page to reflect the changes on the English?

**Comment by Syracopoulos** [comment]
Yes, if the English edits are accepted - they need to be reflected on the French page

**Comment by shawnthompson** [comment]
All pages on our site need to have a descriptive text in plain language below the heading on every page.

This text is used in many places throughout the site.

**Comment by Syracopoulos** [comment]
We changed it on the landing page, I want the same edits to be reflected on the page itself

**Comment by Syracopoulos** [comment]
Et voici le francais!
[Bonnes pratiques pour les événements virtuels accessibles FR.docx](https://github.com/gc-da11yn/gc-da11yn.github.io/files/14172316/Bonnes.pratiques.pour.les.evenements.virtuels.accessibles.FR.docx)
