### ISSUE TITLE
Broken TOC links on French page of Accessible Events

### ISSUE THREAD

**Issue by Syracopoulos** [gc-da11yn/gc-da11yn.github.io#576]
### What page is the change request for? Please supply the URI.

https://a11y.canada.ca/fr/bonnes-pratiques-pour-les-evenements-virtuels-accessibles/index.html

### Approval needed?

None

### Who shall do the work?

- [ ] I will do it, I want to contribute
- [X] I am asking for someone else to please do the work

### Additional context

The links to the page content from the table of contents are broken

**Comment by shawnthompson** [comment]
Can we fix this on the other requests to change the page?

#577, #570, #566

**Comment by shawnthompson** [comment]
@Syracopoulos can you confirm this is still the case? They seem to be working for me.

**Comment by Syracopoulos** [comment]
@shawnthompson you are correct! They are all working now. Good to close :)
