### ISSUE TITLE
[CHANGE] New community to promote

### ISSUE THREAD

**Issue by JulieBB23** [gc-da11yn/gc-da11yn.github.io#583]
### What page is the change request for? Please supply the URI.

https://a11y.canada.ca/en/community-directory/index.html

### Approval needed?

Yes, I need to approve this request before change goes live

### Yes, please send a request to the following person?

julie.belisleboutet@csps-efpc.gc.ca

### Who shall do the work?

- [ ] I will do it, I want to contribute
- [X] I am asking for someone else to please do the work

### Timeline

ASAP

### Additional context

[Accessible Communications CoP Description BIL.docx](https://github.com/gc-da11yn/gc-da11yn.github.io/files/14886270/Accessible.Communications.CoP.Description.BIL.docx)
Please add that description for the community, on the [community page](https://a11y.canada.ca/en/community-directory/index.html) in both language.

**Comment by shawnthompson** [comment]
Do you think "GCpedia page" is good link text for this link?

Visit our [GCpedia page](https://www.gcpedia.gc.ca/wiki/Communications_community_office_-_PLA#Community_of_Practice_on_Accessible_Communications) for more information.

Would this be better?

Visit the  [Community of Practice on Accessible Communications](https://www.gcpedia.gc.ca/wiki/Communications_community_office_-_PLA#Community_of_Practice_on_Accessible_Communications) page on GCPedia for more information.

**Comment by shawnthompson** [comment]
This breaks the expected look and behaviour of the other sections / links on the page:

The other blocks have heading with links and descriptions below them.

But this one has the link in the description and not the heading.

![image](https://github.com/gc-da11yn/gc-da11yn.github.io/assets/2575266/67f9332b-ca43-426c-a819-8e3e55799182)

versus

![image](https://github.com/gc-da11yn/gc-da11yn.github.io/assets/2575266/1f9ceaa9-1266-4a24-a1eb-515e2d1bef78)

This text is also very long compared to the other descriptions on the page.

![image](https://github.com/gc-da11yn/gc-da11yn.github.io/assets/2575266/ba955573-d167-4e9a-8401-ecee53baaef0)

**Comment by shawnthompson** [comment]
My suggestion is:

![image](https://github.com/gc-da11yn/gc-da11yn.github.io/assets/2575266/7660ed7c-e1ce-4c88-8efb-493784472655)
