### ISSUE TITLE
Multiple changes on English page being promoted by PWD Network

### ISSUE THREAD

**Issue by Syracopoulos** [gc-da11yn/gc-da11yn.github.io#584]
### What page is the change request for? Please supply the URI.

https://a11y.canada.ca/en/making-accessible-emails/

### Approval needed?

None

### Who shall do the work?

- [x] I will do it, I want to contribute
- [ ] I am asking for someone else to please do the work

### Additional context

1. Replace the space between the "Grade" and "8" with a non-breaking space "&nbsp

![8f995bf7-ba83-4bd7-b985-798680ec5fa0](https://github.com/gc-da11yn/gc-da11yn.github.io/assets/153029264/f8e4f545-a3ce-4317-b191-a9f195c69895)

2. Change "you" to "your"
![d2fcdde6-7bd9-49eb-b59a-a4518ab4867f](https://github.com/gc-da11yn/gc-da11yn.github.io/assets/153029264/65038966-8aa7-46ae-b89c-7e4f38ba2dfb)

3. Make: 
"(" strong and
"." not-strong
![c604c81f-a279-44c0-8c37-db9f8a35d25f](https://github.com/gc-da11yn/gc-da11yn.github.io/assets/153029264/43214d5e-2835-4894-9d79-10aeda5dbb93)

4. Missing period.
![67f4b8f2-3a75-4295-be38-4417520ca670](https://github.com/gc-da11yn/gc-da11yn.github.io/assets/153029264/f7af1135-879e-45de-ad0c-f51292d58cd0)

5. Remove period after "read"
Remove second period after ")" it is redundant.  End of line should read ", etc.)"
![fe8eb1e3-a35b-4fec-ac11-b7280e83364e](https://github.com/gc-da11yn/gc-da11yn.github.io/assets/153029264/cf15fbd0-ce5d-4af8-a468-db675754653d)

6. Remove both hyphens
add semi-colon
add period at the end of the list.
![0f48a0ff-f058-4c89-9c23-ac2c422db4be](https://github.com/gc-da11yn/gc-da11yn.github.io/assets/153029264/68be845b-c60d-46f8-bd61-3dfbd3556c88)

7. Remove periods
![4a947081-8531-4b23-8eb2-e75c366f0702](https://github.com/gc-da11yn/gc-da11yn.github.io/assets/153029264/95d53056-8cb1-4c2a-b1d2-d37a98465855)

**Comment by shawnthompson** [comment]
This is the working page on Github:

[gc-da11yn.github.io/src/pages/en/making-accessible-emails.md at new-site-structure · gc-da11yn/gc-da11yn.github.io](https://github.com/gc-da11yn/gc-da11yn.github.io/blob/new-site-structure/src/pages/en/making-accessible-emails.md)
