### ISSUE TITLE
[BUG] Wrong wording for French 

### ISSUE THREAD

**Issue by kimviens** [gc-da11yn/gc-da11yn.github.io#595]
### Describe the bug

Page: [Exigences en matière de technologies de l’information et des communications (TIC) accessibles - Boîte à outils de l'accessibilité numérique](https://a11y.canada.ca/fr/exigences-en-matiere-de-technologies-de-l-information-et-des-communications-tic-accessibles/index.html)

"4.2.6 Utilisation sans capacité vocale:" should be "4.2.6 Utilisation sans capacité vocale ou avec une capacité vocale limitée:"

**Comment by shawnthompson** [comment]
This change is to "official" text that was copied over from other resources. Requesting approval to change from the procurement team.

**Comment by shawnthompson** [comment]
Updated to the URL to the mentioned page:

https://a11y.canada.ca/fr/exigences-en-matiere-de-technologies-de-linformation-et-des-communications-tic-accessibles/

**Comment by Silverhustle** [comment]
Page to review: 

- https://deploy-preview-622--a11ycanada.netlify.app/fr/exigences-en-matiere-de-technologies-de-linformation-et-des-communications-tic-accessibles/
