### ISSUE TITLE
[CHANGE] Section headings on How to create accessible documents in Microsoft 365 page are missing id tags.

### ISSUE THREAD

**Issue by LABowden** [gc-da11yn/gc-da11yn.github.io#598]
### What page is the change request for? Please supply the URI.

https://a11y.canada.ca/en/how-to-create-accessible-documents-in-microsoft-365/

### Approval needed?

None

### Who shall do the work?

- [ ] I will do it, I want to contribute
- [X] I am asking for someone else to please do the work

### Additional context

I noticed that the page How to create accessible documents in Microsoft 365 section headings are missing the id tag which would allow people to be able to send a link directly to the section for other users to reference. All the other pages Accessible Excel workbooks in Microsoft 365, Accessible PDF documents in Microsoft 365, Accessible PowerPoint presentations in Microsoft 365, Accessible Visio drawings in Microsoft 365, and Accessible Word documents in Microsoft 365 appear to have the id tag for the section headings.

**Comment by shawnthompson** [comment]
Thank you very much @LABowden. We've added the IDs to the headings as you requested. Normally they are done automatically in markdown files but because there weren't writing in markdown we had to convert them.

This issue will be closed once #619 is merged.

Thanks again.
