### ISSUE TITLE
[CHANGE] Add a new resource under Additional Resources

### ISSUE THREAD

**Issue by JulieBB23** [gc-da11yn/gc-da11yn.github.io#602]
### What page is the change request for? Please supply the URI.

https://a11y.canada.ca/en/additional-resources/

### Approval needed?

No

### Who shall do the work?

- [ ] I will do it, I want to contribute
- [X] I am asking for someone else to please do the work

### Additional context

[Écriture inclusive – Lignes directrices et ressources](https://www.noslangues-ourlanguages.gc.ca/fr/cles-de-la-redaction/ecriture-inclusive-lignes-directrices-ressources)
Consultez des articles approfondis sur des principes et des procédés permettant d’écrire de façon inclusive en français et accédez à d’autres ressources portant sur ce sujet

[Inclusive writing – Guidelines and resources](https://www.noslangues-ourlanguages.gc.ca/en/writing-tips-plus/inclusive-writing-guidelines-resources)
Consult in-depth articles on the principles and techniques of inclusive writing in English, and access other resources on the topic.

**Comment by shawnthompson** [comment]
@JulieBB23 can you please supply us with a Word document with track changes so we are clear on where to put these new links on the page?

Please copy the full page content to a Word document and turn track changes on before making the change.

Thanks,

Your friendly neighbourhood developers :)

**Comment by shawnthompson** [comment]
I'm going to place it under [Development](https://a11y.canada.ca/en/additional-resources/#development).

**Comment by shawnthompson** [comment]
Ready for review:

https://deploy-preview-612--a11ycanada.netlify.app/en/additional-resources
https://deploy-preview-612--a11ycanada.netlify.app/fr/ressources-additionnelles

**Comment by JulieBB23** [comment]
Good to go thanks
