### ISSUE TITLE
Changes to English and French Word checklists

### ISSUE THREAD

**Issue by Syracopoulos** [gc-da11yn/gc-da11yn.github.io#628]
### What page is the change request for? Please supply the URI.

https://a11y.canada.ca/en/microsoft-document-compliance-checklist/

### Approval needed?

None

### Who shall do the work?

- [ ] I will do it, I want to contribute
- [X] I am asking for someone else to please do the work

### Additional context

Original request for changes from Julie BB and Laurence.

**Comment by Syracopoulos** [comment]
[Current DAT content Word checklist EN.docx](https://github.com/user-attachments/files/16786484/Current.DAT.content.Word.checklist.EN.docx)
[Current DAT content Word checklist FR.docx](https://github.com/user-attachments/files/16786485/Current.DAT.content.Word.checklist.FR.docx)

**Comment by Silverhustle** [comment]
Pages to review: 
EN: https://deploy-preview-648--a11ycanada.netlify.app/en/microsoft-document-compliance-checklist/
FR: https://deploy-preview-648--a11ycanada.netlify.app/fr/liste-de-verification-de-la-conformite-des-documents-microsoft/

**Comment by shawnthompson** [comment]
Reopening this issue to because we are adding links to the Success Criterion numbers on the check lists
