### ISSUE TITLE
Additional resources on accessible meetings and events

### ISSUE THREAD

**Issue by Syracopoulos** [gc-da11yn/gc-da11yn.github.io#633]
### What page is the change request for? Please supply the URI.

[Additional resources on accessible meetings and events - Digital Accessibility Toolkit (canada.ca)](https://a11y.canada.ca/en/additional-resources-on-accessible-meetings-and-events/index.html)

### Approval needed?

None

### Who shall do the work?

- [ ] I will do it, I want to contribute
- [X] I am asking for someone else to please do the work

### Additional context

[Ressources additionnelles sur les réunions et événements accessibles FR.docx](https://github.com/user-attachments/files/16933096/Ressources.additionnelles.sur.les.reunions.et.evenements.accessibles.FR.docx)
[Additional resources on accessible meetings and events EN.docx](https://github.com/user-attachments/files/16933097/Additional.resources.on.accessible.meetings.and.events.EN.docx)

**Comment by shawnthompson** [comment]
I cleaned up the request code, not sure what happened but it's all good :)
