### ISSUE TITLE
[BUG] Multi language markdown files - not properly marked up

### ISSUE THREAD

**Issue by shawnthompson** [gc-da11yn/gc-da11yn.github.io#68]
## Required information

**Describe the bug**
Markdown files that are multi language don't have proper markup when language changes from English to French. 

All French text should be wrapped in a `<div lang="fr">` because Github's pages are declared as `lang="en"`. 

**To Reproduce**

View source:

```
<html lang="en" data-color-mode="auto" data-light-theme="light" data-dark-theme="dark">
```

**Expected behaviour**
When a screen reader reads the French text, it should read it in French.

**Who shall do the work?**
I'll leave it open for anyone to take.

## Additional information (optional)

**Additional context**
 
I've opened this issue with Github to try to create a markdown way of switching languages on `.md` files using Markdown.

[Multi language page in GFM #243](https://github.com/github/cmark-gfm/issues/243)

**Comment by shawnthompson** [comment]
To clarify we should be wrapping all our French text in `.md` files with a `<div lang="fr">`.

Making sure we leave an empty space between the `HTML` and `markdown`.

Don't do this:
```
<div lang="fr">
## Boîte à outils d'accessibilité numérique
...
</div>
```

**Like this:**

```
<div lang="fr">
...

## Boîte à outils d'accessibilité numérique

</div>

**Comment by csps-snap** [comment]
there's definitely something I'm not getting.
1. there's french lenguage in english pages ? the html lang attribute seems to be doing its job fine?
![image](https://user-images.githubusercontent.com/41083520/142425927-778304e0-57c4-4672-8b35-15c52b95587a.png)


2. I've looked for .md files in the _src folder and all I could find was the blogpost (in either language)
- the french one was empty and the english one only had english content. I couldn'T find any more .md files (unless I go in the node modules which is normal, but none of our business.

where did I go wrong ?
