### ISSUE TITLE
Automate a sitemap with nodeJS

### ISSUE THREAD

**Issue by shawnthompson** [gc-da11yn/gc-da11yn.github.io#72]
Use nodeJS to create a sitemap file

* [ ] find a npm package that would build a sitemap.xml
* [ ] run against the files in the `_site` folder

**Comment by ericmoore123** [comment]
Starting sitemap development this week after long delay.

**Comment by shawnthompson** [comment]
Actually we can do it with 11ty. I was able to do it during the Thursday meeting.

I'm using this from the starter page:

https://github.com/11ty/eleventy-base-blog/blob/master/page-list.njk
