### ISSUE TITLE
Add link checker to project

### ISSUE THREAD

**Issue by shawnthompson** [gc-da11yn/gc-da11yn.github.io#74]
Using NodeJs add a link testing 
* [ ] find nodejs package that would do this for us
* [ ] add to npm task

**Comment by shawnthompson** [comment]
[link-checker - npm](https://www.npmjs.com/package/link-checker)

**Comment by acev0010** [comment]
A pull request was merged some time ago that added the "npm run link-check" command to check for the links inside the markdown files before build. Would that close this issue or a different link checker should be added to scan the links that are already in the website?

Here is that PR: https://github.com/gc-da11yn/gc-da11yn.github.io/pull/399
