### ISSUE TITLE
Web Design

### ISSUE THREAD

**Issue by JulieBB23** [gc-da11yn/gc-da11yn.github.io#95]
Create documentation on how to contribute to the web design parts of this project

**Comment by shawnthompson** [comment]
Problem with Web Design is we need to follow the Canada.ca specs and should be pushing any changes we think that are needed to TBS.

**Comment by Prantoo9** [comment]
Problem with Web Design is we need to follow the Canada.ca specs and should be pushing any changes we think that are needed to TBS.

**Comment by JulieBB23** [comment]
The design has been established since that issue was open.
